CREATE SCHEMA IF NOT EXISTS mb_test;

CREATE SEQUENCE IF NOT EXISTS mb_test.hibernate_sequence START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS mb_test.default_sequence_generator START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS mb_test.revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS mb_test.revinfo
(
    rev      INTEGER NOT NULL DEFAULT NEXTVAL('mb_test.revinfo_seq') PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE IF NOT EXISTS mb_test.score_board
(
    id                 BIGINT       NOT NULL PRIMARY KEY,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_date_time  TIMESTAMP    NOT NULL,
    modified_date_time TIMESTAMP    NOT NULL,
    home_team_name     VARCHAR(255) NOT NULL,
    away_team_name     VARCHAR(255) NOT NULL,
    home_team_score    INT          NOT NULL,
    away_team_score    INT          NOT NULL
);

CREATE TABLE IF NOT EXISTS mb_test.score_board_aud
(
    id                     BIGINT  NOT NULL,
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    deleted                BOOLEAN,
    deleted_mod            BOOLEAN,
    created_date_time      TIMESTAMP,
    created_date_time_mod  BOOLEAN,
    modified_date_time     TIMESTAMP,
    modified_date_time_mod BOOLEAN,
    home_team_name         VARCHAR(255),
    home_team_name_mod     BOOLEAN,
    away_team_name         VARCHAR(255),
    away_team_name_mod     BOOLEAN,
    home_team_score        INT,
    home_team_score_mod    BOOLEAN,
    away_team_score        INT,
    away_team_score_mod    BOOLEAN,
    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES mb_test.revinfo (rev)
);

CREATE TABLE IF NOT EXISTS mb_test.tutorials
(
    id                 BIGINT    NOT NULL,
    deleted            BOOLEAN   NOT NULL DEFAULT FALSE,
    created_date_time  TIMESTAMP NOT NULL,
    modified_date_time TIMESTAMP NOT NULL,
    title              VARCHAR(255),
    description        VARCHAR(255),
    published          BOOLEAN
);

INSERT INTO mb_test.score_board (id, deleted, created_date_time, modified_date_time, home_team_name, away_team_name,
                                 home_team_score, away_team_score)
VALUES (NEXTVAL('mb_test.default_sequence_generator'), FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1' DAY,
        'Uruguay', 'Italy', 6, 6),
       (NEXTVAL('mb_test.default_sequence_generator'), FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '2' DAY,
        'Spain', 'Brazil', 10, 2),
       (NEXTVAL('mb_test.default_sequence_generator'), FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '3' DAY,
        'Mexico', 'Canada', 0, 5),
       (NEXTVAL('mb_test.default_sequence_generator'), FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '4' DAY,
        'Argentina', 'Australia', 3, 1),
       (NEXTVAL('mb_test.default_sequence_generator'), FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '5' DAY,
        'Germany', 'France', 2, 2);

CREATE TABLE IF NOT EXISTS mb_test.coffee
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)   NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2) NOT NULL,
    size        VARCHAR(20)    NOT NULL,
    CONSTRAINT coffee_price_positive CHECK (price > 0),
    CONSTRAINT coffee_size_valid CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE'))
);

CREATE INDEX IF NOT EXISTS idx_coffee_name ON mb_test.coffee (name);
CREATE INDEX IF NOT EXISTS idx_coffee_size ON mb_test.coffee (size);
CREATE INDEX IF NOT EXISTS idx_coffee_price ON mb_test.coffee (price);

CREATE TABLE IF NOT EXISTS mb_test.orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT,
    customer_name VARCHAR(200)   NOT NULL,
    order_date    TIMESTAMP      NOT NULL,
    total_amount  DECIMAL(10, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    CONSTRAINT orders_total_positive CHECK (total_amount >= 0),
    CONSTRAINT orders_status_valid CHECK (status IN ('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_name ON mb_test.orders (customer_name);
CREATE INDEX IF NOT EXISTS idx_orders_status ON mb_test.orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_date ON mb_test.orders (order_date);

CREATE TABLE IF NOT EXISTS mb_test.order_items
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id  BIGINT         NOT NULL,
    coffee_id BIGINT         NOT NULL,
    quantity  INTEGER        NOT NULL,
    price     DECIMAL(10, 2) NOT NULL,
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_price_positive CHECK (price > 0),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES mb_test.orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_coffee FOREIGN KEY (coffee_id) REFERENCES mb_test.coffee (id)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON mb_test.order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_coffee_id ON mb_test.order_items (coffee_id);

-- Sample coffee products for the coffee shop demo
-- Reset auto-increment sequences
ALTER TABLE mb_test.order_items
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mb_test.orders
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mb_test.coffee
    ALTER COLUMN id RESTART WITH 1;

-- Small coffees
INSERT INTO mb_test.coffee (name, description, price, size)
VALUES ('Espresso', 'Rich and bold single shot of espresso', 2.50, 'SMALL'),
       ('Americano', 'Espresso with hot water', 3.00, 'SMALL'),
       ('Macchiato', 'Espresso with a dollop of foam', 3.25, 'SMALL');

-- Medium coffees
INSERT INTO mb_test.coffee (name, description, price, size)
VALUES ('Cappuccino', 'Espresso with steamed milk and foam', 4.50, 'MEDIUM'),
       ('Latte', 'Espresso with steamed milk', 4.75, 'MEDIUM'),
       ('Flat White', 'Espresso with velvety microfoam', 4.50, 'MEDIUM'),
       ('Mocha', 'Espresso with chocolate and steamed milk', 5.25, 'MEDIUM'),
       ('Caramel Macchiato', 'Vanilla and espresso with caramel drizzle', 5.50, 'MEDIUM');

-- Large coffees
INSERT INTO mb_test.coffee (name, description, price, size)
VALUES ('Large Latte', 'Double shot espresso with extra steamed milk', 5.75, 'LARGE'),
       ('Large Cappuccino', 'Double shot espresso with steamed milk and foam', 5.50, 'LARGE'),
       ('Large Mocha', 'Double shot espresso with chocolate and steamed milk', 6.25, 'LARGE'),
       ('Caffe Misto', 'Brewed coffee with steamed milk', 4.50, 'LARGE'),
       ('Cold Brew', 'Smooth cold-steeped coffee', 5.00, 'LARGE'),
       ('Iced Latte', 'Espresso with cold milk over ice', 5.50, 'LARGE'),
       ('Vanilla Latte', 'Espresso with vanilla and steamed milk', 6.00, 'LARGE');

-- Sample orders to demonstrate AOT query capabilities (H2 compatible timestamps)
-- Sample orders to demonstrate AOT query capabilities (PostgreSQL compatible timestamps)
INSERT INTO mb_test.orders (customer_id, customer_name, order_date, total_amount, status)
VALUES (1, 'Alice Johnson', CURRENT_TIMESTAMP - INTERVAL '2' day, 8.25, 'DELIVERED'),
       (2, 'Bob Smith', CURRENT_TIMESTAMP - INTERVAL '1' day, 12.50, 'DELIVERED'),
       (1, 'Alice Johnson', CURRENT_TIMESTAMP - INTERVAL '5' hour, 5.75, 'READY'),
       (3, 'Charlie Brown', CURRENT_TIMESTAMP - INTERVAL '2' hour, 15.00, 'PREPARING'),
       (4, 'Diana Prince', CURRENT_TIMESTAMP - INTERVAL '30' minute, 4.50, 'PENDING'),
       (2, 'Bob Smith', CURRENT_TIMESTAMP - INTERVAL '10' minute, 9.00, 'PENDING');

-- Sample order items to demonstrate relationships and JOINs
-- Alice's first order (2 days ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (1, 4, 1, 4.50), -- Cappuccino
       (1, 2, 1, 3.00), -- Americano
       (1, 5, 1, 4.75);
-- Latte

-- Bob's first order (1 day ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (2, 9, 2, 5.75), -- 2x Large Latte
       (2, 1, 1, 2.50);
-- Espresso

-- Alice's recent order (5 hours ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (3, 9, 1, 5.75);
-- Large Latte

-- Charlie's preparing order (2 hours ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (4, 11, 1, 6.25), -- Large Mocha
       (4, 7, 1, 5.25),  -- Mocha
       (4, 2, 1, 3.00);
-- Americano

-- Diana's pending order (30 minutes ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (5, 4, 1, 4.50);
-- Cappuccino

-- Bob's recent pending order (10 minutes ago)
INSERT INTO mb_test.order_items (order_id, coffee_id, quantity, price)
VALUES (6, 7, 1, 5.25), -- Mocha
       (6, 2, 1, 3.00); -- Americano
